GCC_OPTION= -Wall -pedantic

all:  benchmark  exercicio02 x1strcat x2strcat xstrcat xstrlen

benchmark: 
	gcc -g $(GCC_OPTION) -o $@ $^

exercicio02: 
	gcc -g $(GCC_OPTION) -o $@ $^
	
x1strcat: 
	gcc -g $(GCC_OPTION) -o $@ $^

x2strcat: 
	gcc -g $(GCC_OPTION) -o $@ $^
	
xstrcat:
	gcc -g $(GCC_OPTION) -o $@ $^
	
xstrlen:
	gcc -g $(GCC_OPTION) -o $@ $^
