GCC_OPTION= -Wall -pedantic
all:  exercicio1 

#exercicio1: exercicio1.c exercicio1.h
#	gcc -g $(GCC_OPTION) -o $@ $^


exercicio1: exercicio1.c exercicio1.h astrcat.s
	gcc -g $(GCC_OPTION) -o $@ $^
	
#exercicio3: exercicio3.c exercicio3.h
#	gcc -g $(GCC_OPTION) -o $@ $^
