GCC_OPTION= -Wall -pedantic
all: exercicio1 exercicio2 exercicio3

exercicio1: exercicio1.c exercicio1.h
	gcc -g $(GCC_OPTION) -o $@ $^

exercicio2: exercicio2.c exercicio2.h
	gcc -g $(GCC_OPTION) -o $@ $^
	
exercicio3: exercicio3.c exercicio3.h
	gcc -g $(GCC_OPTION) -o $@ $^
